### ISSUE TITLE
Problem when installing on Odoo 1

### ISSUE THREAD

**Issue by chrbarth82** [OCA/currency#17] opened 2018-04-17 13:53 UTC
Hi all,

When trying to install the Currency Rate Updater on our Odoo 11, I receive the following error - could you please help:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 967, in _validate_fields
    check(self)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 333, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 717, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 667, in apply_view_inheritance
    source = self.apply_view_inheritance(source, view_id, model, root_id=root_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 666, in apply_view_inheritance
    source = self.apply_inheritance_specs(source, specs_tree, view_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 644, in apply_inheritance_specs
    self.raise_view_error(_("Element '%s' cannot be located in parent view") % tag, inherit_id)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 506, in raise_view_error
    raise ValueError(message)
ValueError: Element '<label for="module_currency_rate_live">' cannot be located in parent view

Error context:
View `currency_rate_update.res.config.settings.form`
[view_id: 1591, xml_id: n/a, model: res.config.settings, parent_id: 617]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.exceptions.ValidationError: ('Error while validating constraint\n\nElement \'<label for="module_currency_rate_live">\' cannot be located in parent view\n\nError context:\nView `currency_rate_update.res.config.settings.form`\n[view_id: 1591, xml_id: n/a, model: res.config.settings, parent_id: 617]', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 646, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 307, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 339, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 332, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 927, in __call__
    return self.method(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/http.py", line 512, in response_wrap
    response = f(*args, **kw)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 928, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/web/controllers/main.py", line 916, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 446, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/module/module.py", line 539, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 343, in load_modules
    loaded_modules, update_module)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 242, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 156, in load_module_graph
    _load_data(cr, module_name, idref, mode, kind='data')
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/modules/loading.py", line 94, in _load_data
    tools.convert_file(cr, module_name, filename, idref, mode, noupdate, kind, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 788, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 849, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 748, in parse
    exc_info[2]
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 741, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/tools/convert.py", line 651, in _tag_record
    id = self.env(context=rec_context)['ir.model.data']._update(rec_model, self.module, res, rec_id or False, not self.isnoupdate(data_node), noupdate=self.isnoupdate(data_node), mode=self.mode)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_model.py", line 1467, in _update
    record = record.create(values)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 401, in create
    return super(View, self).create(self._compute_defaults(values))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3286, in create
    self._fields[key].determine_inverse(record)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/fields.py", line 1078, in determine_inverse
    getattr(records, self.inverse)()
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 269, in _inverse_arch
    view.write(data)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/base/ir/ir_ui_view.py", line 417, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3008, in write
    self._write(old_vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 3161, in _write
    self._validate_fields(vals)
  File "/opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/models.py", line 971, in _validate_fields
    raise ValidationError("%s\n\n%s" % (_("Error while validating constraint"), tools.ustr(e)))
odoo.tools.convert.ParseError: "Error while validating constraint

Element '<label for="module_currency_rate_live">' cannot be located in parent view

Error context:
View `currency_rate_update.res.config.settings.form`
[view_id: 1591, xml_id: n/a, model: res.config.settings, parent_id: 617]
None" while parsing /opt/bitnami/apps/odoo/lib/odoo-11.0.post20171218-py3.6.egg/odoo/addons/currency_rate_update/views/res_config_settings.xml:8, near
<record id="view_res_config_settings" model="ir.ui.view">
        <field name="name">currency_rate_update.res.config.settings.form</field>
        <field name="model">res.config.settings</field>
        <field name="inherit_id" ref="account.res_config_settings_view_form"/>
        <field name="arch" type="xml">
            <data><field name="module_currency_rate_live" position="before">
                <field name="auto_currency_up" class="oe_inline"/>
            </field>
            <label for="module_currency_rate_live" position="before">
                <label for="auto_currency_up"/>
                <div class="text-muted">
                    Update exchange rates automatic from currency_rate_update module
                </div>
            </label>
        </data></field>
    </record>

**Comment by pedrobaeza** [comment] 2018-04-17 13:55
Hi, this seems something related to your deployment, as all the recent builds are correctly deployed in runbot (https://runbot.odoo-community.org/runbot), so please be sure you are following the proper installation steps.

I'm closing this issue now, but if you feel this can be something reproducible with other steps, please reply adding all the additional information for reproducing the problem.

**Closed as completed by pedrobaeza** 2018-04-17 13:55 UTC

**Comment by misuv** [comment] 2018-04-17 15:20
I just had the same problem: see currency_rate_update install error #18

here are the install steps I used:

1. I installed all dependencies:  

base | Installed
mail | Installed
account | Installed

2. used Putty to install it:

cd /tmp
sudo git clone -b 11.0 https://github.com/OCA/currency.git
sudo mv /tmp/currency/currency_rate_update  /odoo/custom/addons

3. restarted Odoo server - there is no error in server log

4. tried to install Currency Rate Updater on our Odoo 11 - received error

what I did wrong, because I found no install steps in documentation?

(also I updated Odoo)

**Comment by moylop260** [comment] 2018-04-17 15:25
I can't reproduce it

Result using `--without-demo=all`:
 - <img width="1275" alt="screen shot 2018-04-17 at 10 22 32" src="https://user-images.githubusercontent.com/6644187/38879618-62c4cc98-4229-11e8-8367-e0370c60595f.png">

Result without using `--without-demo=all`:
 - <img width="1280" alt="screen shot 2018-04-17 at 10 25 01" src="https://user-images.githubusercontent.com/6644187/38879696-9c480a84-4229-11e8-83a4-60684ad87310.png">

**Comment by moylop260** [comment] 2018-04-17 15:35
It's very strange that 2 people have the same error.
I'm looking for other reason and I found a posible reason to reproduce it

We have duplicated a module name `currency_rate_update`:
 - https://github.com/OCA/account-financial-tools/blob/10.0/currency_rate_update/views/account_config_settings.xml

(But I didn't see it migrated to version 11.0)

Could you upload a screenshot of all pages of the module (Settings/Apps search currency_rate_update) using debug mode (in the url `...?debug/...`) in order to get other clues about.

**Comment by misuv** [comment] 2018-04-17 15:40
![image](https://user-images.githubusercontent.com/13998625/38880505-9578bc18-426e-11e8-8bfa-a5c11447463f.png)

I know the other module, I didn't install it

![image](https://user-images.githubusercontent.com/13998625/38880612-cdb1e42e-426e-11e8-982d-373146a38817.png)

**Comment by moylop260** [comment] 2018-04-17 15:42
Thanks
Could you create an empty database and install just the `currency_rate_update` module, please?

**Comment by moylop260** [comment] 2018-04-17 15:45
In fact, the traceback told us `odoo-11.0.post20171218-py3.6.egg`
- You are using python3.6 and you must use py3.5
- You are using a too old odoo-11.0 version (2017-12-18, please upgrade it)

And repeat the steps with an empty database in order to confirm an environment error.

**Comment by pedrobaeza** [comment] 2018-04-17 15:46
It's not duplicated, but the module has been moved from OCA/account-financial-tools (last version: 10) to OCA/currency (in v11). They are not using the correct one I think.

**Comment by misuv** [comment] 2018-04-17 15:56
I upgrade it before I installed currency update module

with an empty database the module is installing fine. (same Odoo, same python, same server)

could be a problem from another custom module?

**Comment by moylop260** [comment] 2018-04-17 15:57
I confirm that this issue is reproduced it using a old 11.0 odoo version:
Steps to reproduce it:

 - Use a old version of odoo11.0 <=2017-12:
  - Using in odoo local repository `git reset --hard 8836ad52741`
- See the old date of this version
  - Using in odoo local repository `git show 8836ad52741`
```bash
commit 8836ad52741ff661248a4e268a195da1e645c684 (HEAD -> 11.0-odoo)
Author: Florent de Labarre <florent.mirieu@gmail.com>
Date:   Sun Dec 17 21:32:28 2017 +0100

    [IMP] stock: detail in product error
...
```
- Install `currency_rate_update` module in a empty database:
 - `./odoo-bin -d new_db -i currency_rate_update --addons-path=~/odoo/currency,addons --logfile=out.txt --stop-after-init`

- See the error:
 - <img width="1269" alt="screen shot 2018-04-17 at 10 53 16" src="https://user-images.githubusercontent.com/6644187/38881527-91024f14-422d-11e8-8edc-f8a8cf408b21.png">

You need upgrade your odoo and upgrade the original views of `account` module (maybe a `-u all`)

**Comment by misuv** [comment] 2018-04-17 16:06
I upgrade it Odoo before installed the module (with error)

with an empty database is installing fine
 
how to  upgrade the original views of account module?

**Comment by moylop260** [comment] 2018-04-17 16:07
FYI you will need the following commit applied:
 - https://github.com/odoo/odoo/commit/3715244a51a2aa382e98da69905a4aa6759b50e0

Then you need a odoo11.0 release >= 10/Feb/2018

@feketemihai Maybe we can use a dual compatibility using other field (without changes) in order to add the inherited field without issues with all 11.0 odoo version.

@misuv @chrbarth82 for now you will need to upgrade odoo 11.0 version

**Comment by moylop260** [comment] 2018-04-17 16:09
> how to upgrade the original views of account module?

`... -d {your_database} -u account`

Or use `Upgrade` button from `Settings / Apps` on `account` module.

**Comment by pedrobaeza** [comment] 2018-04-17 16:10
The prerequisite should be to have an upgraded Odoo I think. I don't see working in a compatibility that's is solved through an update.

**Comment by misuv** [comment] 2018-04-17 16:25
1. I upgraded the apps
2. I upgraded Odoo using:
`cd /odoo

cd odoo-server

sudo git fetch origin 11.0

sudo git reset --hard origin/11.0

sudo service odoo-server restart -u all -d [db_name] 
`
3. still same error

**Comment by pedrobaeza** [comment] 2018-04-17 18:39
> sudo service odoo-server restart -u all -d [db_name]

That command is not correct for updating all

**Comment by misuv** [comment] 2018-04-17 19:28
I found the solution
1. I unistall Acounting management by By Cubic ERP, Odoo
2. I installed Currency update module (no errors)
3. Reinstall  Acounting management by By Cubic ERP, Odoo (no errors)

**Comment by pedrobaeza** [comment] 2018-04-17 20:08
Then the problem can be in that module, that is inheriting the bad way (making a replace for example).

**Comment by feketemihai** [comment] 2018-04-17 20:10
It was with currency_rate_module since the label was changed from string to id in v11 base odoo.

Sent from my Huawei Mobile

-------- Original Message --------
Subject: Re: [OCA/currency] Problem when installing on Odoo 1 (#17)
From: "Pedro M. Baeza"
To: OCA/currency
CC: Mihai FEKETE ,Mention


Then the problem can be in that module, that is inheriting the bad way (making a replace for example).

**Comment by pedrobaeza** [comment] 2018-04-17 20:14
OK, thanks for the explanation.

**Comment by feketemihai** [comment] 2018-04-18 05:23
@pedrobaeza I think you can close it, solution is in #19 .
